Information_System/Controllers/CreateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Information_System.Models;
using System.Data.SqlClient;
using System.Text;
using System.IO;
using System.Net;
using System.Web.Mvc;
using System.Globalization;

namespace Information_System.Controllers
{
    public class CreateController : Controller
    {
        InFunction Fn = new InFunction();
        public string url = "http://10.145.163.14/";
        static string Newid = null;
        DateTime dtwarn = DateTime.Parse(DateTime.UtcNow.ToString("dd/MMM/yyyy HH:mm:ss"));
        public CreateController()
        {
            try
            {
                url = System.Web.HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority).Equals(null) ? "" : System.Web.HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority);
            }
            catch
            {
                url = "";
            }
      
        }

        //REQ
        public ActionResult RequirementInfoList()
        {
            try
            {
                if (string.IsNullOrEmpty(Convert.ToString(Session["login_id"])))
                {
                    return View("../Home/Login");
                }
                else
                {
                    List<Department> res = new List<Department>();
                    using (SqlConnection con = new SqlConnection(Fn.connString))
                    {
                        con.Open();
                        using (SqlCommand cmd = new SqlCommand(null, con))
                        {
                            cmd.CommandText = " SELECT Dept_ID, Dept_Name FROM tbl_Dept where Dept_Status = 'T' ";
                            SqlDataReader reader = cmd.ExecuteReader();
                            while (reader.Read())
                            {
                                Department model = new Department();
                                model.DEP_ID = reader["Dept_ID"].ToString();
                                model.DEP_NAME = reader["Dept_Name"].ToString();
                                res.Add(model);
                            }
                            ViewData["DepList"] = res;
                        }
                        con.Close();
                    }

                    return View();
                }
            }
            catch
            {
                return View("../Home/Login");
            }
         
        }
        public ActionResult ReceivedRequirment(string id)
        {
            try
            {
                if (string.IsNullOrEmpty(Convert.ToString(Session["login_id"])))
                {
                    return View("../Home/Login");
                }
                else
                {
                    RequestDocModel model = new RequestDocModel();
                    using (SqlConnection con = new SqlConnection(Fn.conRTCStr))
                    {
                        con.Open();
                        using (SqlCommand cmd = new SqlCommand(null, con))
                        {
                            SqlDataReader reader = null;
                            cmd.CommandText = $@" SELECT TOP 1 DO.STATUS INFO_STATUS, r.*,  CONCAT(EMP.empTitleEng,' ', emp.empNameEng) AS ISSUE_NAME, EMP.empEmail , empa.empEmail as APPROVE_EMAIL 
                                          ,APPROVE_NAME = STUFF((SELECT ', ' + CONCAT(emp2.empTitleEng, emp2.empNameEng) FROM TBL_TECH_IS_REQUEST_APPROVE RA JOIN db_employee.dbo.tbl_employee EM ON RA.APPROVE_ID = EM.empId
                                            JOIN db_employee.dbo.tbl_employee emp2 ON RA.APPROVE_ID = emp2.empId
                                           WHERE REQUEST_ID = { Fn.getSQL(id) } ORDER BY APPROVE_LEVEL ASC FOR XML PATH('')), 1, 1, '') 

                                                                                 , APPROVEEMAIL = ( SELECT TOP(1) empa.empEmail FROM 
                                             TBL_TECH_IS_REQUEST_APPROVE RA LEFT JOIN  db_employee.dbo.tbl_employee empa 
                                             on empa.empId = RA.APPROVE_ID 
                                             WHERE REQUEST_ID = {Fn.getSQL(id)}
                                             )

                                         FROM TBL_TECH_IS_REQUEST r LEFT JOIN db_employee.dbo.tbl_employee emp
                                         on emp.empId = r.ISSUE_ID  LEFT JOIN db_employee.dbo.tbl_employee empa
                                         on empa.empId = r.APPROVE_BY   LEFT JOIN TBL_TECH_IS_DOCINFO DO
                                         ON r.IS_ID = DO.REQUEST_NO
                                          LEFT JOIN db_employee.dbo.tbl_employee emp2 ON r.APPROVE_BY = emp2.empId" +
                                                                                      " WHERE IS_ID = " + Fn.getSQL(id) +
                                              " AND APPROVE_STATUS IN ('APPROVED','REJECT','TE-REJECT') ";
                            reader = cmd.ExecuteReader();
                            if (reader.Read())
                            {
                                model.IS_ID = reader["IS_ID"].ToString();
                                model.IS_NO = reader["IS_NO"].ToString();
                                model.PLANT = reader["PLANT"].ToString();
                                model.DEPARTMENT = reader["DEPARTMENT"].ToString();
                                model.SUBJECT = reader["SUBJECT"].ToString();
                                model.REASON_EXPLAIN = reader["REASON_EXPLAIN"].ToString();
                                model.START_PROD_MONTH = reader["START_PROD_MONTH"].ToString();
                                model.DOCUMENT_DATA_OF_CHANGE = reader["DOCUMENT_DATA_OF_CHANGE"].ToString();
                                model.PARTS_CODE = reader["PARTS_CODE"].ToString();
                                model.WATCH_CODE = reader["WATCH_CODE"].ToString();
                                model.CLASSIFICATION = reader["CLASSIFICATION"].ToString();
                                model.ISSUE_ID = reader["ISSUE_ID"].ToString();
                                model.ISSUE_DATE = Convert.ToDateTime(reader["ISSUE_DATE"]);
                                model.ISSUE_NAME = reader["ISSUE_NAME"].ToString();
                                model.APPROVE_STATUS = reader["APPROVE_STATUS"].ToString();
                                model.ISSUE_EMAIL = reader["empEmail"].ToString();
                                model.APPROVE_EMAIL = reader["APPROVEEMAIL"].ToString();
                                model.APPROVE_NAME = reader["APPROVE_NAME"].ToString();
                                model.INFO_STATUS = reader["INFO_STATUS"].ToString();
                                model.APPROVE_COMMENT = reader["APPROVE_COMMENT"].ToString();
                                model.DETAILS = reader["DETAILS"].ToString();
                                if (reader["WARNING_DATE"] != null)
                                {
                                    if (reader["WARNING_DATE"].ToString() != "")
                                    {
                                        model.WARNING_DATE = Convert.ToDateTime(reader["WARNING_DATE"]).AddHours(8);
                                    }

                                }

                            }
                            reader.Close();

                            cmd.CommandText = " SELECT PATCH FROM TBL_TECH_IS_FILES F " +
                                              " JOIN TBL_TECH_IS_REQUEST R ON R.IS_ID = F.IS_ID " +
                                              " WHERE F.IS_ID = " + Fn.getSQL(id); // +
                                                                                   // " AND R.APPROVE_STATUS = 'APPROVED' ";
                            reader = cmd.ExecuteReader();
                            while (reader.Read())
                            {
                                model.GET_FILE_LIST.Add(reader["PATCH"].ToString());
                            }

                            reader.Close();
                            cmd.CommandText = " SELECT A.*, CONCAT(E.empNameEng, ' ',E.empLnameEng) NAME, convert(varchar, APPROVE_DATE, 22) DATE , E.empEmail as EMPEMAIL FROM TBL_TECH_IS_REQUEST_APPROVE A " +
                                              " JOIN db_employee.dbo.tbl_employee E ON A.APPROVE_ID = E.empId WHERE REQUEST_ID = " + Fn.getSQL(id);
                            reader = cmd.ExecuteReader();
                            while (reader.Read())
                            {
                                APPROVE_REQUEST_LIST al = new APPROVE_REQUEST_LIST();
                                al.APPROVE_ID = reader["APPROVE_ID"].ToString();
                                al.APPROVE_LEVEL = reader["APPROVE_LEVEL"].ToString();
                                al.APPROVE_DATE = reader["DATE"].ToString();
                                al.APPROVE_EMAIL = reader["EMPEMAIL"].ToString();
                                al.APPROVE_NAME = reader["NAME"].ToString();
                                al.COMMENT = reader["COMMENT"].ToString();
                                al.STATUS = reader["STATUS"].ToString();
                                model.APPROVE_LIST.Add(al);
                            }

                        }
                        con.Close();
                    }
                    return View(model);
                }
            }
            catch
            {
                return View("../Home/Login");
            }
           

        }
        public ActionResult CreateRequirementDoc(string id)
        {
            try
            {
                System.Diagnostics.Debug.WriteLine("CreateRequirementDoc");
                if (string.IsNullOrEmpty(Convert.ToString(Session["login_id"])))
                {
                    return View("../Home/Login");
                }
                else

Information_System/Views/Approve/ApproveRequirement.cshtml
@{
    ViewBag.Title = "ApproveRequirement";
    List<Information_System.Models.RequestDocModel> d = null;
    if (ViewData["RequirementList"] != null)
    {
        d = ViewData["RequirementList"] as List<Information_System.Models.RequestDocModel>;
    }
}

<style>
    .width-200 {
        width: 200px;
    }
</style>

<div style="background-color: white; padding: 16px;" class="mt-2">
    <h2>Requirement list pending approval</h2>
    @*<div class="row">
        <div class="col-lg-2">
            <button type="button" class="btn btn-success width-200" data-toggle="modal" id="btnApprove" data-target="#approveAllModel" disabled="disabled">Approve</button>
        </div>
        <div class="col-lg-2">
            <button type="button" class="btn btn-danger width-200" data-toggle="modal" id="btnReject" data-target="#rejectModel" disabled="disabled">Reject</button>
        </div>
    </div>*@

    @if (d != null )
    {
        <div class="mt-3 table-responsive" id="tbList">
            <table class="tb-radius table table-hover table-striped">
                <thead style="background-color: #1F618D; color: white;">
                    <tr>
                        @*<th class="text-center"><input type="checkbox" id="chkAll" /></th>*@
                        <th>Subject</th>
                        <th>Reason Explain</th>
                        <th>Issue By</th>
                        <th>Issue Date</th>
                        <th>Plant/Department</th>
                        <th class="text-center">Action</th>
                    </tr>
                </thead>
                <tbody class="table-body" id="tbody">
                    @foreach (var l in d)
                    {
                        <tr>
                            @*<td class="text-center"><input type="checkbox" onclick="chkSelectd();" id="@l.IS_ID" /></td>*@
                            <td>@l.SUBJECT</td>
                            <td>@l.REASON_EXPLAIN</td>
                            <td>@l.ISSUE_NAME</td>
                            <td>@l.ISSUE_DATE</td>
                            <td>@l.DEPARTMENT</td>
                            <td class='text-center'><a href="@Url.Action("ApproveRequest","Create")/@l.IS_ID" target="_blank" title="click for approve requirement"><img src="~/Image/journal-check.svg" width="21" /></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
    else
    {
        <div id="Nolist" class="mt-3">
            <p>No result.</p>
        </div>
    }

</div>